services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mor", "-d", "hypno_analytics"]
      interval: 10s
      retries: 5

  vector_db:
    build:
      context: ./vector_db
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./hypnoq_index:/app/hypnoq_index
    ports:
      - "5000:5000"
    environment:
      - DATA_PATH=/app/data
      - INDEX_NAME=/app/hypnoq_index
  
  models:
    build:
      context: ./models
      dockerfile: Dockerfile
    env_file:
    - .env
    volumes:
      - ./hypnoq_index:/app/hypnoq_index
    ports:
    - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - INDEX_NAME=/app/hypnoq_index
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - models

# Define the volume at the bottom of the file
volumes:
  postgres_data:

