version: '3.8'
services:
  vector_db:
    build:
      context: ./vector_db
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./hypnoq_index:/app/hypnoq_index
    ports:
      - "5000:5000"
    environment:
      - DATA_PATH=/app/data
      - INDEX_NAME=/app/hypnoq_index
  
  models:
    build:
      context: ./models
      dockerfile: Dockerfile
    env_file:
    - .env
    volumes:
      - ./hypnoq_index:/app/hypnoq_index
    ports:
    - "8000:8000"
    depends_on:
      - vector_db
    environment:
      - INDEX_NAME=/app/hypnoq_index
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - vector_db


