services:
  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: ""
    envVars:
      - key: CHATBOT_URL
        value: "http://models:8000/hypno-bot"
    autoDeploy: true

  - type: web
    name: models
    env: docker
    dockerfilePath: ./models/Dockerfile
    envVars:
      - key: INDEX_NAME
        value: "/app/hypnoq_index"
    autoDeploy: true

  - type: worker
    name: vector-db-worker
    env: docker
    dockerfilePath: ./vector_db/Dockerfile
    envVars:
      - key: DATA_PATH
        value: "/app/data"
      - key: INDEX_NAME
        value: "/app/hypnoq_index"
    autoDeploy: true
