services:
  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: ""
    envVars:
      - key: CHATBOT_URL
        value: "http://models:8000/hypno-bot"
    autoDeploy: true

  - type: web
    name: models
    env: docker
    dockerfilePath: ./models/Dockerfile
    envVars:
      - key: INDEX_NAME
        value: "/app/hypnoq_index"
    autoDeploy: true

  - type: web
    name: vector-db-web
    env: docker
    dockerfilePath: ./vector_db/Dockerfile
    envVars:
      - key: DATA_PATH
        value: "/app/data"
      - key: INDEX_NAME
        value: "/app/hypnoq_index"
    autoDeploy: true

# Add PostgreSQL Database
databases:
  - name: hypnoq-db
    databaseName: hypno_qna_postgres
    user: mor
    ipAllowList: # Optional, configure your IP if necessary
      - source: 0.0.0.0/0
        description: allow-all
    envVars:
    - key: DATABASE_URL
      value: postgresql://mor:U8zYiRWc1LRqT201HhA4qluRdptHWT24@dpg-crp87dtds78s73d5s390-a/hypno_analytics

