{
 "title": "ChatBot Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Relevant Answers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  relevance,\n  COUNT(*) as count\nFROM conversations\nGROUP BY relevance"
    }
   ]
  },
  {
   "title": "Tumbs up",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(CASE WHEN feedback > 0 THEN 1 ELSE 0 END) as thumbs_up,\n  SUM(CASE WHEN feedback < 0 THEN 1 ELSE 0 END) as thumbs_down\nFROM feedback"
    }
   ]
  },
  {
   "title": "Recent Conversations",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  question,\n  answer,\n  relevance\nFROM conversations\nORDER BY timestamp DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "description": "show how long a use need to wait to get a response from our bot",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  response_time\nFROM conversations\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Response Time Split",
   "type": "timeseries",
   "description": "show how long a use need to wait to get a response from our bot",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  qna_time, eval_time\nFROM conversations\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Tokens used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  total_tokens\nFROM conversations\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Tokens used split",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  prompt_tokens, completion_tokens\nFROM conversations\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Evaluation Tokens used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  eval_total_tokens\nFROM conversations\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Evaluation Tokens used split",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  eval_prompt_tokens, eval_completion_tokens\nFROM conversations\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Total Tokens used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  total_tokens + eval_total_tokens\nFROM conversations\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Total Tokens used split",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  total_tokens, eval_total_tokens\nFROM conversations\nORDER BY timestamp"
    }
   ]
  }
 ]
}